version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: eduresources-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: academic_resources
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - eduresources-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/academic_resources --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eduresources-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DATABASE_NAME=academic_resources
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - EMERGENT_LLM_KEY=${EMERGENT_LLM_KEY}
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - eduresources-network
    command: uvicorn server:app --host 0.0.0.0 --port 8001 --reload

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: eduresources-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - eduresources-network
    command: yarn start

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  backend_uploads:
    driver: local

networks:
  eduresources-network:
    driver: bridge